FROM rust:1.81-slim-bullseye AS build

RUN apt-get update && apt-get install -y \
    build-essential \
    pkg-config \
    libssl-dev

WORKDIR /usr/src/app

COPY src src
COPY Cargo.toml .
COPY Cargo.lock .

RUN cargo build --release